services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://chatbot:5000
    depends_on:
      - chatbot
    networks:
      - app-network
    restart: unless-stopped

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/key.json
    env_file:
      - ./chatbot/.env
    environment:
      - FLASK_ENV=production
      - PORT=5000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    

networks:
  app-network:
    driver: bridge
